spring:
  profiles:
    active: ${CATCONNECT_SPRING_PROFILE_ACTIVE:local}
  jackson:
    time-zone: Asia/Seoul  # API 응답 직렬화
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul  # DB 저장

springdoc:
  api-docs:
    path: /api-docs  # (선택) 기본은 /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # (선택) 기본은 /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true