server:
  port: ${CATCONNECT_TOMCAT_PORT:8081}
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${CATCONNECT_PROD_DB_URL}/${CATCONNECT_PROD_DB_NAME}
    username: ${CATCONNECT_PROD_DB_USERNAME}
    password: ${CATCONNECT_PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver